[package]
name = "advent2021"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/thejpster/aoc2021.git"
homepage = "https://github.com/thejpster/aoc2021"
description = "My Advent of Code 2021 solutions"

[dependencies]
